config_rewrite:
  replace: ['hidden']
content:
  field_districts:
    type: select2_entity_reference
    weight: 29
    region: content
    settings:
      width: 100%
      autocomplete: false
      match_operator: STARTS_WITH
      match_limit: 10
    third_party_settings: {  }
hidden:
  created: true
  hide_description: true
  ontologyword_ids: true
  show_www: true
  subgroup: true
