config_rewrite:
  replace: [
    'dependencies',
    'display.default.cache_metadata.contexts',
    'display.block.cache_metadata.contexts'
  ]
dependencies:
  config:
    - core.entity_view_mode.tpr_unit.teaser_with_image
    - taxonomy.vocabulary.neighbourhoods
  module:
    - address
    - helfi_tpr
    - taxonomy
    - user
display:
  default:
    display_options:
      fields:
        name:
          group_column: entity_id
        address__postal_code:
          group_column: entity_id
        address__address_line1:
          group_column: entity_id
        address__address_line2:
          group_column: entity_id
        id:
          id: id
          table: tpr_unit_field_data
          field: id
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: tpr_unit
          entity_field: id
          plugin_id: field
          label: ''
          exclude: true
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: string
          settings:
            link_to_entity: false
          group_column: entity_id
          group_columns:
            entity_id: entity_id
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
        name_1:
          id: name_1
          table: taxonomy_term_field_data
          field: name
          relationship: field_districts
          group_type: group
          admin_label: ''
          entity_type: taxonomy_term
          entity_field: name
          plugin_id: term_name
          label: ''
          exclude: true
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: string
          settings:
            link_to_entity: false
          group_column: entity_id
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          convert_spaces: false
      filters:
        combine:
          fields:
            name_1: name_1
        provided_languages_value:
          id: provided_languages_value
          table: tpr_unit__provided_languages
          field: provided_languages_value
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: tpr_unit
          entity_field: provided_languages
          plugin_id: string
          operator: '='
          value: ''
          group: 1
          exposed: true
          expose:
            operator_id: provided_languages_value_op
            label: 'Provided languages'
            description: null
            use_operator: false
            operator: provided_languages_value_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: provided_languages_value
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            placeholder: null
          is_grouped: true
          group_info:
            label: ''
            description: ''
            identifier: provided_languages_value
            optional: true
            widget: select
            multiple: true
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items:
              1:
                title: 'Only show service points where services are available in Swedish.'
                operator: '='
                value: sv
        field_districts_target_id:
          id: field_districts_target_id
          table: tpr_unit__field_districts
          field: field_districts_target_id
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: taxonomy_index_tid
          operator: empty
          value: {  }
          group: 2
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          reduce_duplicates: false
          vid: neighbourhoods
          type: select
          hierarchy: false
          limit: true
          error_message: true
        langcode_1:
          id: langcode_1
          table: taxonomy_term_field_data
          field: langcode
          relationship: field_districts
          group_type: group
          admin_label: ''
          entity_type: taxonomy_term
          entity_field: langcode
          plugin_id: language
          operator: in
          value:
            '***LANGUAGE_language_content***': '***LANGUAGE_language_content***'
          group: 2
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
      relationships:
        field_districts:
          id: field_districts
          table: tpr_unit__field_districts
          field: field_districts
          relationship: none
          group_type: group
          admin_label: 'field_districts: Taxonomy term'
          plugin_id: standard
          required: false
      filter_groups:
        operator: AND
        groups:
          1: AND
          2: OR
      group_by: true
    cache_metadata:
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - url.query_args
        - user
        - user.permissions
  block:
    cache_metadata:
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - url.query_args
        - user
        - user.permissions
  entity_reference:
    display_options:
      defaults:
        relationships: false
      relationships: {  }
