_core:
  default_config_hash: g4xLZ2eKdkd2lO31Wp099a3bY5ZYZoE_xjR8BwROUMM
langcode: en
calculators:
  home_care_service_voucher:
    active: false
    json: '{}'
    label: 'Home care service voucher'
  home_care_client_fee:
    active: false
    json: '{}'
    label: 'Home care client fee'
  continuous_housing_service_voucher:
    active: false
    json: '{}'
    label: '24-hour housing service voucher'
  families_home_services_client_fee:
    active: false
    json: '{}'
    label: 'Families home services client fee'
  early_childhood_education_fee:
    active: false
    json: '{}'
    label: 'Early childhood education fee'
