on:
  workflow_dispatch:
  repository_dispatch:
    types: [ build_artifact ]
  schedule:
    - cron:  '0 0 * * 0'
name: Build artifacts
env:
  COMPOSE_PROJECT_NAME: helfi-sote
  DRUPAL_BUILD_FROM_SCRATCH: true
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/city-of-helsinki/drupal-php-docker:8.0

    services:
      db:
        image: druidfi/db:mysql5.7-drupal
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build project
        run: composer install

      - name: Build project
        run: |
          drush si -y && drush cr && drush si --existing-config -y && drush cim -y
          drush sql-dump --result-file=latest.sql

      - name: Save latest database dump for robo tests
        uses: actions/upload-artifact@v2
        with:
          name: latest.sql
          path: latest.sql
          retention-days: 10
